### ISSUE TITLE
How to train the model on kitti dataset？

### ISSUE THREAD

**Issue by 406143996** [fudan-zvg/DeepInteraction#18]
Thank the author for the great work!

I want to run through this model on the kitti format data set. After modifying the data part in the configuration file and the relevant part in the train_pipeline, I find it is always difficult to run through, and the following bugs appear. Is there a configuration file description for kitti dataset in this code?

`Traceback (most recent call last):
  File "tools/train.py", line 249, in <module>
    main()
  File "tools/train.py", line 238, in main
    train_model(
  File "/public/chenrunze/wl/mm2/mmdetection3d-0.17.1/mmdet3d/apis/train.py", line 28, in train_model
    train_detector(
  File "/public/chenrunze/miniconda3/envs/di_help_zq/lib/python3.8/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/public/chenrunze/miniconda3/envs/di_help_zq/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/public/chenrunze/miniconda3/envs/di_help_zq/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/public/chenrunze/miniconda3/envs/di_help_zq/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/public/chenrunze/miniconda3/envs/di_help_zq/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/public/chenrunze/miniconda3/envs/di_help_zq/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/public/chenrunze/miniconda3/envs/di_help_zq/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/public/chenrunze/miniconda3/envs/di_help_zq/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/public/chenrunze/wl/mm2/mmdetection3d-0.17.1/mmdet3d/models/detectors/base.py", line 59, in forward
    return self.forward_train(**kwargs)
  File "/public/chenrunze/zq/DeepInteraction-main/projects/mmdet3d_plugin/models/detectors/deepinteraction.py", line 200, in forward_train
    img_feats, pts_feats = self.extract_feat(
  File "/public/chenrunze/zq/DeepInteraction-main/projects/mmdet3d_plugin/models/detectors/deepinteraction.py", line 140, in extract_feat
    new_img_feat, new_pts_feat = self.imgpts_neck(img_feats[0], pts_feats[0], img_metas, pts_metas)
TypeError: 'NoneType' object is not subscriptable`

**Comment by xtk8532704** [comment]
There are some modules in the code that depend on the nuscenes dataset. You need to read the code carefully and modify them.

**Comment by HydrogenWasser** [comment]
@406143996 hi, have u trained deepinteraction on kitti? i modified it to suit kitti dataset but the training result is sooo bad, i wonder if i made some mistakes.

**Comment by enestydarealmc** [comment]
> @406143996 hi, have u trained deepinteraction on kitti? i modified it to suit kitti dataset but the training result is sooo bad, i wonder if i made some mistakes.

can you please share your config?
I'd be very grateful. Thank you

**Comment by HydrogenWasser** [comment]
> > @406143996 hi, have u trained deepinteraction on kitti? i modified it to suit kitti dataset but the training result is sooo bad, i wonder if i made some mistakes.
> 
> can you please share your config? I'd be very grateful. Thank you

same bad result, cant train deepinteraction on kitti

**Comment by iyi-alam** [comment]
@HydrogenWasser  were you able to train the model on KITTY? One stage training is a complete failure leading to matched IOUs of < 2%. I think some critical training details have not been disclosed by authors. I doubt it may be related to dense depth prediction or object query initialization.
