### ISSUE TITLE
About the 'mmdet3d_plugin'

### ISSUE THREAD

**Issue by zjr-bit** [fudan-zvg/DeepInteraction#22]
Hi, thanks for your great work. And I have one question about the `mmdet3d_plugin` in your code.
I guess that the plugin module is not used after it is imported in `train.py`. So, could you please tell me why do you design this step?
Thanks!

**Comment by Gmonster-24** [comment]
我遇到了这样的错误：
projects.mmdet3d_plugin
Traceback (most recent call last):
  File "/media/lab509/gta/mmdetection3d/DeepInteraction/tools/train.py", line 248, in <module>
    main()
  File "/media/lab509/gta/mmdetection3d/DeepInteraction/tools/train.py", line 118, in main
    plg_lib = importlib.import_module(_module_path)
  File "/home/lab509/anaconda3/envs/gta-di/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'projects
请问应该如何解决？

> Hi, thanks for your great work. And I have one question about the `mmdet3d_plugin` in your code. I guess that the plugin module is not used after it is imported in `train.py`. So, could you please tell me why do you design this step? Thanks!
