### ISSUE TITLE
error :No module named 'projects'

### ISSUE THREAD

**Issue by study0101** [fudan-zvg/DeepInteraction#29]
Thanks for your great work. I have a problem when testing DeepInteraction-base model with the given checkpoint.
I used command :
python tools/test.py projects/configs/nuscenes/Fusion_0075_refactor.py trained/Fusion_0075_refactor.pth  --eval=bbox
but errors appear
Traceback (most recent call last):
  File "tools/test.py", line 246, in <module>
    main()
  File "tools/test.py", line 138, in main
    plg_lib = importlib.import_module(_module_path)
  File "/sdbdata/zjy/anaconda3/envs/deep/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'projects'

My environment ：

TorchVision: 0.10.1+cu111
OpenCV: 4.6.0
MMCV: 1.3.18
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: 11.1
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.17.1

**Comment by Gmonster-24** [comment]
I also met the same problem. Have you solved it？

**Comment by Alexander0Yang** [comment]
When you directly run tools/test.py for testing, you should add the current path to the environment variable PYTHONPATH.
